### ISSUE TITLE
add http basic authentication for /admin

### ISSUE THREAD

**Issue by flyerhzm** [transist/echidna-rails#72]
I created a pull request for rails_admin https://github.com/transist/echidna-rails/pull/71, I don't want to add any authorization in code now, please add http basic authentication in nginx

**Comment by 0x1b2c** [comment]
Actually I've added http basic auth for the entire site in nginx, but seems someone commented out it couple days ago. I think it's necessary to protect the entire site since everyone can watch any information without the protection.

Do you think it's necessary to show the admin in today's demo? If not, I think it's better to add the authorization code later then merge the pull request.

**Comment by flyerhzm** [comment]
We don't want http basic auth for the entire site because Scott want to show it and don't like it.

I think we don't want to show the admin, it's added to us, checking tweets easier. I'm fine to add authorization code later

**Comment by 0x1b2c** [comment]
OK, I'll change to use the http basic auth only for /admin.
